import math

MINIMAP_SIZE = 10 #45 is max

RES = WIDTH, HEIGHT = 1440, 900
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60

CAMERA_POS = 1.5, 5
CAMERA_ANGLE = 0
CAMERA_SPEED = 0.0035
CAMERA_ANGULAR_SPEED = 0.002
CAMERA_SIZE_SCALE = 60


FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2